// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFF2WvPDNijtcDK4fVO5uI8LdmDF_97RE',
    appId: '1:499635113389:web:41ec0758fcf5cb88f6e524',
    messagingSenderId: '499635113389',
    projectId: 'twitter-cd49a',
    authDomain: 'twitter-cd49a.firebaseapp.com',
    storageBucket: 'twitter-cd49a.appspot.com',
    measurementId: 'G-13DK615XLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUxpv5pJXOcBOeZUYwsj4t8mXQ_XfEMsw',
    appId: '1:499635113389:android:0a87711ece5d4eeef6e524',
    messagingSenderId: '499635113389',
    projectId: 'twitter-cd49a',
    storageBucket: 'twitter-cd49a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-9fi71K2YmIfl-xyRjOYKWfGKGPaakwQ',
    appId: '1:499635113389:ios:22f46ef8d3ee8fa9f6e524',
    messagingSenderId: '499635113389',
    projectId: 'twitter-cd49a',
    storageBucket: 'twitter-cd49a.appspot.com',
    iosBundleId: 'com.example.flutterGetxExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-9fi71K2YmIfl-xyRjOYKWfGKGPaakwQ',
    appId: '1:499635113389:ios:13b91cda2e55b965f6e524',
    messagingSenderId: '499635113389',
    projectId: 'twitter-cd49a',
    storageBucket: 'twitter-cd49a.appspot.com',
    iosBundleId: 'com.example.flutterGetxExample.RunnerTests',
  );
}
